language: cpp
dist: focal

compiler:
  - gcc
  - clang

script:
  - cmake -S . -B _build
  - cmake --build _build
  - ./_build/hello_world_application/hello_world
  - printf "1 0 -1\n" | ./_build/solver_application/solver
